name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: anomaly51/github-actions-toolkit/.github/workflows/harbor-argocd-app.yml@main
    with:
      app-name: pingme-backend
      notification-title: PingMe Backend
      image-repository: harbor.api-api-api.com/pingme/backend
    secrets: inherit
