name: Build and Push to Forgejo

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: argocd-runners

    steps:
      - uses: actions/checkout@v4

      - run: docker build -t 192.168.1.154/forgejoadmin/pingme-backend:latest .

      - run: echo "ForgejoPassword123!" | docker login 192.168.1.154 -u forgejoadmin --password-stdin

      - run: docker push 192.168.1.154/forgejoadmin/pingme-backend:latest

